
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gdsc
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.naver.com
    port: 465
    username: ofi1234@naver.com
    password: aksl4224!
    properties:
      debug: false
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
          trust: smtp.naver.com
  redis:
    host: localhost
    port: 6379



logging:
  level:
    org.hibernate.sql: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true